### PR TITLE
Email various types

### PR DESCRIPTION
**Pull request by ryanpavlik24**
Added in multiple other email templates. Also added an automated job to send birthday emails to the team

### CODE REVIEW

**Comment by xkjjx** [comment]
image


Got this error when I tried sending an individual email to myself

**Comment by ryanpavlik24** [comment]
@xkjjx can you take a look at this again when you get chance?

**Comment by xkjjx** [comment]
Before seeding the database, only my account was in it. So I tried sending a test message to all members and encountered this error:
image

**Comment by ryanpavlik24** [comment]
Yeah I can add error handling. My assumption is that no one is "active"

**Comment by ryanpavlik24** [comment]
I need to clean up some tests too. This can be merged tomorrow

**Comment by xkjjx** [comment]
How is active status determined?

**Comment by ryanpavlik24** [comment]
Grad Date > today.

Felt like this was the best option rather than having to have people mark themselves inactive once they graduate. Up to alternatives though. That logic is very simple and can easily be adjusted

**Comment by ryanpavlik24** [comment]
@xkjjx  can you take a look at this tomorrow when you get a chance? Will test on Heroku tomorrow with the automation

**Review by xkjjx — APPROVED** [review]
Looks good!

**Pull request merged**
