### PR TITLE
Calendar features

### PR DESCRIPTION
**Pull request by ryanpavlik24**
All calendar features are complete

### CODE REVIEW

**Comment by xkjjx** [comment]
Overall looks very good! Only thing is currently in the edit event view, the "all-day event" functionality is not working

A nice cherry on top would be that when you edit the event, all the previous event start/end times and description should be imported over.

Let me know if you want to work on those in this PR or save those for another.

**Comment by ryanpavlik24** [comment]
> Overall looks very good! Only thing is currently in the edit event view, the "all-day event" functionality is not working
> 
> A nice cherry on top would be that when you edit the event, all the previous event start/end times and description should be imported over.
> 
> Let me know if you want to work on those in this PR or save those for another.

I have the all-day thing fixed and the start/end time will be coming with that.

**Comment by ryanpavlik24** [comment]
@xkjjx  Can you confirm this working on your end now?

**Review by xkjjx — APPROVED** [review]
Approving because all base functionality is complete.

For some reason, the time only gets carried over for all day events, otherwise when clicking edit, the start and end times are blank.

**Comment by ryanpavlik24** [comment]
Thats interesting. Mine carries over for both. I will clarify locally again. If it still works for me we can see how the functionality works on Heroku and then go from there

**Pull request merged**
