### PR TITLE
Photos page

### PR DESCRIPTION
**Pull request by saradyl-tamu**
created photos table, CRUD, and styling

### CODE REVIEW

**Review by ryanpavlik24 — CHANGES_REQUESTED** [review]
Need to figure out why every file is changes. Likely an issue with the spacing. @xkjjx has gotten pretty good with figuring this out.

**Comment by xkjjx** [comment]
> Need to figure out why every file is changes. Likely an issue with the spacing. @xkjjx has gotten pretty good with figuring this out.

It's because this branch was checked out from main instead of dev. We can either merge the changes from dev into this branch, which would mean going through all these files manually and fixing the merge conflicts, but I think the better choice is to simply redo all these changes on a new branch that's checked out of dev instead. @saradyl-tamu , do you want to do that, or I can do that as well.

**Comment by xkjjx** [comment]
I am working on copying these changes on another branch that is out of dev instead @ryanpavlik24 @saradyl-tamu .

**Comment by xkjjx** [comment]
I am going to change the branch I am merging to from dev to main just to see the changes clearer.

**Comment by xkjjx** [comment]
See PR #33

**Pull request closed without merging**
