### PR TITLE
Member page

### PR DESCRIPTION
**Pull request by saradyl-tamu**
Created member page (still need to combine with member directory page on logged in view but might need Kevin to do that so I don't accidentally mess up his code for the directory)

### CODE REVIEW

**Review by ryanpavlik24 — APPROVED** [review]
Looks good to me! If you want to merge now I think you can. If you want to wait for Kevin on Sunday and combine the 2 pages using this branch that works too

**Review by PearlynnT — COMMENTED** [review]
Tests for this page doesn't seem to have been written yet. Do we need to write some test cases for this?

**Review by xkjjx — APPROVED** [review]
Looks good. I made it so the link changes destination depending on if the user is logged in, and also this page is fully view only with no authentication, so it made sense for me to merge it's functionality with the PagesController. Since it's view only, we likely don't need any tests either @PearlynnT . I added a couple of tests to verify the intended functionality of the navbar.

**Comment by ryanpavlik24** [comment]
I still approve of this FYI

**Pull request merged**
