### PR TITLE
Sponsorship logo

### PR DESCRIPTION
**Pull request by PearlynnT**
### For sponsorship
- seeded database with sponsor information
- added a column to the sponsorship entity
- used cloudinary for sponsor logo
- added access controls
### For location
- Refactored code and created a form partial
- Added input validation checks
- Added unit tests
- Added dropdown for country field
- Fixed seed data

### CODE REVIEW

**Review by ryanpavlik24 — APPROVED** [review]
If this will fix the dev deployment we should try to rush this to being merged @xkjjx

**Comment by xkjjx** [comment]
> If this will fix the dev deployment we should try to rush this to being merged @xkjjx

I think there's a chance that the changes here might break other tests - I am taking a look right now.

**Review by PearlynnT — COMMENTED** [review]
just realised that uploading an image to sponsorship does not work (it defaults to the placeholder image), taking a look at it now

edit: an image url is not created

**Comment by xkjjx** [comment]
For the projects to reference the location correctly, we do need some accurate location id to be passed in. In my latest commit, I am going to change the seeding just a bit.

**Comment by xkjjx** [comment]
> just realised that uploading an image to sponsorship does not work (it defaults to the placeholder image), taking a look at it now
> 
> edit: an image url is not created

After this is fixed, I think we are ready to merge this.

**Comment by PearlynnT** [comment]
> For the projects to reference the location correctly, we do need some accurate location id to be passed in. In my latest commit, I am going to change the seeding just a bit.

Oops my bad, I force pushed my commit, your changes are lost

**Pull request merged**
