### PR TITLE
Tests for loc photos

### PR DESCRIPTION
**Pull request by saradyl-tamu**

### CODE REVIEW

**Review by ryanpavlik24 — APPROVED** [review]
Looks good to me. I think @xkjjx deleted some of the unused files recently. May be worth to wait until everyone has changes added before doing so again

**Comment by saradyl-tamu** [comment]
what's wrong with the delete? It was working locally

**Comment by xkjjx** [comment]
> what's wrong with the delete? It was working locally

It's the same issue I had initially with the deletion for my user CRUD. When I click delete, it takes me to the show instead of processing deletion. Don't use the `data: confirm : {...}` feature and instead just use links - feel free to reference the other CRUD as well.

**Review by xkjjx — APPROVED** [review]
Approved for sprint#2 - any final fine tuning will be addressed in sprint 3.

**Pull request merged**
